import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQueryClient, useSuspenseQuery } from "@tanstack/react-query";
import { useState } from "react";
import { Check, Info } from "lucide-react";
import { Stepper, StepperCard } from "@/components/vayu/Stepper";
import { insertOutreach, outreachQuery } from "@/lib/queries";

export const Route = createFileRoute("/_authenticated/outreach")({
  head: () => ({ meta: [{ title: "VAYU — Outreach Approval" }] }),
  loader: ({ context }) => context.queryClient.ensureQueryData(outreachQuery),
  component: OutreachPage,
  errorComponent: ({ error }) => <div className="p-10 text-coral">{error.message}</div>,
  notFoundComponent: () => <div className="p-10">Not found</div>,
});

const STEPS = [
  { icon: "⚡", label: "Patient Flagged", time: "14:23" },
  { icon: "🤖", label: "AI Outreach Generated", time: "14:24" },
  { icon: "👨‍⚕️", label: "Provider Review", time: "NOW" },
  { icon: "📨", label: "Message Scheduled" },
  { icon: "📋", label: "Logged in EHR" },
];

const MESSAGES: Record<string, string> = {
  en: "Air quality in the Dallas metro area is expected to worsen over the next 48 hours due to elevated ozone and particulate levels. If you have a respiratory condition, we recommend limiting outdoor activity (especially 2–6 PM), keeping rescue inhaler accessible, running AC indoors, and contacting your care team if symptoms worsen. — Your VAYU Care Team",
  es: "Se espera que la calidad del aire en el área metropolitana de Dallas empeore durante las próximas 48 horas debido a niveles elevados de ozono y partículas. Si tiene una condición respiratoria: limite la actividad al aire libre (especialmente 2–6 PM), mantenga su inhalador de rescate accesible, use aire acondicionado en interiores, y comuníquese con su equipo de atención si los síntomas empeoran. — Su equipo VAYU",
};

function OutreachPage() {
  const { data: logs } = useSuspenseQuery(outreachQuery);
  const qc = useQueryClient();
  const [step, setStep] = useState(2);
  const [lang, setLang] = useState<"en" | "es">("en");
  const [approved, setApproved] = useState(false);

  const approveMut = useMutation({
    mutationFn: async () => {
      await insertOutreach({
        patient_id: "TX-301500",
        track: "A",
        message_content: MESSAGES[lang],
      });
    },
    onSuccess: () => {
      setApproved(true);
      setStep(4);
      qc.invalidateQueries({ queryKey: ["outreach_logs"] });
    },
  });

  return (
    <div className="max-w-[1320px] mx-auto px-7 py-7 flex flex-col gap-6">
      <div className="animate-fade-up">
        <h1 className="text-[1.7rem] font-extrabold tracking-tight">48-Hour Approve & Release</h1>
        <p className="text-[0.88rem] text-text-dim mt-1.5">
          Review AI-generated outreach campaigns and approve for delivery to consented patients.
        </p>
      </div>

      <StepperCard>
        <Stepper steps={STEPS} current={step} />
      </StepperCard>

      <div className="grid lg:grid-cols-2 gap-6">
        {/* Campaign details */}
        <section className="bg-card border border-border rounded-[14px] p-6 animate-fade-up">
          <h2 className="text-[1rem] font-bold mb-5">📢 Campaign Details</h2>
          <div className="grid grid-cols-2 gap-4 text-sm">
            <Detail label="Campaign" value="Heat Advisory — Respiratory Panel" full />
            <Detail label="Generated By" value="VAYU AI Worker" />
            <Detail label="Trigger" value="AQI >150 + Heat >100°F" />
            <Detail label="Target Population" value="847 patients (Track A)" />
            <Detail label="Channel" value={<Tag color="teal">SMS</Tag>} />
            <Detail label="Priority" value={<Tag color="coral">Critical</Tag>} />
          </div>
        </section>

        {/* Approval */}
        <section className="bg-card border border-border rounded-[14px] p-6 animate-fade-up">
          <h2 className="text-[1rem] font-bold mb-5">🔐 Approval Controls</h2>
          <div className="flex items-center gap-3 mb-5">
            <label className="text-[0.78rem] font-semibold text-text-dim whitespace-nowrap">
              Schedule:
            </label>
            <select className="flex-1 px-3.5 py-2.5 rounded-lg bg-surface border border-border text-sm focus:outline-none focus:border-teal">
              <option>Immediate</option>
              <option>In 30 minutes</option>
              <option>Tomorrow at 8:00 AM</option>
            </select>
          </div>
          <button
            onClick={() => approveMut.mutate()}
            disabled={approved || approveMut.isPending}
            className={`w-full px-5 py-3.5 rounded-xl font-bold text-[0.95rem] transition-all flex items-center justify-center gap-2 ${
              approved
                ? "bg-teal/20 text-teal border border-teal cursor-default"
                : "bg-gradient-to-r from-teal to-[#00b894] text-[#0a0f1e] hover:shadow-[0_8px_30px_rgba(0,212,170,0.4)] hover:-translate-y-px"
            }`}
          >
            {approved ? (
              <>
                <Check className="w-5 h-5" /> Approved · Sent to 847 patients
              </>
            ) : approveMut.isPending ? (
              "Sending..."
            ) : (
              "✓ Approve & Schedule Campaign"
            )}
          </button>
          <div className="mt-4 px-4 py-3 rounded-lg bg-blue/[0.06] border border-blue/15 text-[0.78rem] text-blue flex items-start gap-2.5">
            <Info className="w-4 h-4 mt-0.5 flex-shrink-0" />
            <span>
              FHIR Progress Note will be automatically documented for all 847 patients upon delivery
              confirmation.
            </span>
          </div>
        </section>
      </div>

      {/* Message preview */}
      <section className="bg-card border border-border rounded-[14px] p-6 animate-fade-up">
        <h2 className="text-[1rem] font-bold mb-5">💬 Message Preview</h2>
        <div className="flex justify-center mb-4">
          <div className="inline-flex border border-border rounded-lg overflow-hidden">
            {(["en", "es"] as const).map((l) => (
              <button
                key={l}
                onClick={() => setLang(l)}
                className={`px-5 py-2 text-[0.78rem] font-semibold transition ${
                  lang === l ? "bg-teal-dim text-teal" : "text-text-dim hover:bg-white/[0.03]"
                }`}
              >
                {l === "en" ? "🇺🇸 English" : "🇪🇸 Español"}
              </button>
            ))}
          </div>
        </div>
        <div className="max-w-md mx-auto bg-surface border border-border rounded-2xl p-5">
          <div className="flex items-center gap-3 pb-3 border-b border-border">
            <div className="w-9 h-9 rounded-full bg-gradient-to-br from-teal to-blue flex items-center justify-center text-xs font-bold text-[#0a0f1e]">
              VA
            </div>
            <div>
              <div className="text-[0.85rem] font-semibold">VAYU</div>
              <div className="text-[0.68rem] text-text-muted">SMS · Now</div>
            </div>
          </div>
          <div className="mt-3 p-4 rounded-2xl bg-teal/[0.06] border border-teal/15 text-[0.82rem] leading-relaxed">
            {MESSAGES[lang]}
          </div>
          <div className="text-[0.66rem] text-text-muted text-right mt-2">Today, 2:24 PM CDT</div>
        </div>
      </section>

      {/* History */}
      <section className="bg-card border border-border rounded-[14px] p-6 animate-fade-up">
        <h2 className="text-[1rem] font-bold mb-4">📋 Outreach History Log</h2>
        <div className="overflow-x-auto">
          <table className="w-full text-sm min-w-[600px]">
            <thead>
              <tr className="text-[0.68rem] uppercase tracking-wider text-text-dim border-b border-border">
                <th className="text-left px-4 py-2.5">Sent At</th>
                <th className="text-left px-4 py-2.5">Patient</th>
                <th className="text-left px-4 py-2.5">Track</th>
                <th className="text-left px-4 py-2.5">Message</th>
              </tr>
            </thead>
            <tbody>
              {logs.map((l) => (
                <tr
                  key={l.id}
                  className="border-b border-border last:border-0 hover:bg-white/[0.02]"
                >
                  <td className="px-4 py-3 text-text-dim">
                    {new Date(l.sent_at).toLocaleString()}
                  </td>
                  <td className="px-4 py-3 font-semibold text-teal">{l.patient_id}</td>
                  <td className="px-4 py-3">
                    <Tag color={l.track === "A" ? "teal" : "amber"}>Track {l.track}</Tag>
                  </td>
                  <td className="px-4 py-3 text-text-dim truncate max-w-md">{l.message_content}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  );
}

function Detail({ label, value, full }: { label: string; value: React.ReactNode; full?: boolean }) {
  return (
    <div className={full ? "col-span-2" : ""}>
      <div className="text-[0.66rem] uppercase tracking-wider text-text-muted font-semibold mb-1">
        {label}
      </div>
      <div className="text-[0.88rem] font-semibold">{value}</div>
    </div>
  );
}

function Tag({
  children,
  color,
}: {
  children: React.ReactNode;
  color: "teal" | "amber" | "coral";
}) {
  const c = { teal: "#00d4aa", amber: "#ffb347", coral: "#ff6b6b" }[color];
  return (
    <span
      className="text-[0.68rem] font-semibold px-2 py-0.5 rounded"
      style={{ background: `${c}1f`, color: c }}
    >
      {children}
    </span>
  );
}
